### ISSUE TITLE
SavageEd v0.10.18 minor bugs

### ISSUE THREAD

**Issue by midaspt** [Androthi/SavageEd#10]
I tested it under Windows 10 2004 (build 19041.388) and found some usability _papercuts_:

- ".LOG[<]" is not inserting date, only time;
- "Edit | Date/Time | Set Date Format..." and "Set Time Format..." dialogs don't respond to Escape or Enter but require mouse click;
- "[mailto:]someone@the.net" is not picked up by URL activation;
- "Help | Documents" would be better formatted to the customary text console 80 columns width;
- Even if the rest of the UI appears crisp, the "Help | About..." dialog looks really fuzzy (also, the URL therein is obsolete);
- Even with "Options | Recent File Options | Open in New Window" set, there's no reason to obey it if there's zero input in the main window;
- Shift+F3 is the more usual shortcut for "Find Previous..."

I hope you find my observations useful. 😃

**Comment by Androthi** [comment]
Thanks. I will look at these issues when I get the chance. Currently in a crunch working long hours.

**Comment by Androthi** [comment]
fixed the log issue

i can't seem to repeat point 2 or 3. maybe it was fixed incidentally. after i upload the latest test version (sometime in the next couple days) please see if this is resolved.

made small update to about dialog .. got rid of obsolete website info

please make the other change suggestions as separate issues so that they won't escape my memory.

**Comment by Androthi** [comment]
Thanks, I'll take a look when I get some time.

The Start Position in the INI file is if you enable the the Remember
Position option and works together with Open Most Recent option. When you
exit, SavageEd stores the cursor position in the text that you were in.
When you start SavageEd again, it will try to jump the cursor to that
position so that you can continue your work where you left off. This may
cause some conflict in LOG files. I haven't done much testing of these
options working with LOG files.

**Comment by Androthi** [comment]
a new beta version will be uploaded soon.

i did some test with the mail links. if you want to use the mailto someone, there can't be a bracket in it. so, in your example, it will try to send a message to "]someone@the.net"
use instead:
mailto:someone@the.net

are there a lot of sites that use the [mailto:] format? if so, i may edit the ']' out inside SavageEd before sending it.

**Comment by midaspt** [comment]
The later is the standard format, in my experience -- although it's nice to have the convenience of simple address activation.

You just need to ensure people are aware of the bracket quirk, IMHO...

Thanks for all the work. Patiently waiting for the new version. 🆒

**Comment by Androthi** [comment]
It's another buggy behavior in richedit. This past week I've been
researching another platform to rewrite SavageEd from scratch, maybe using
openGL and a different programming language.
But this would look very different from the current version and the
filesize of just opening a blank window is already in the 300k range. heh.

I will consider the option of editing the mailto: input and manually
removing the ']' bracket that richedit inserts into the string. I also
haven't tested a complete mailto: to autofill all the fields like cc,
subject, etc.

I have uploaded v0.10.30 to the pre-release branch.

**Comment by Androthi** [comment]
In the latest stable release, 0.30.35, we now actively remove ']' characters in link strings, so this should no longer be an issue.
Also, you can click on a string such as:

[mailto:]name@mail.com?subject=The%20subject&body=This%20is%20a%20message%20body

And this will auto fill the person's email, subject line and body with the text. It will work as long as there are no spaces in the text. %20 indicates the space character.

**Comment by midaspt** [comment]
Great news! Thank you. 😎
