### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by midaspt** [Androthi/SavageEd#2]
Hi and thanks for the remarkable work with **SavageEd2** and previously **SavageEd**.

I have a (couple of) feature request(s) I'd like to submit to your consideration, in full awareness you consider **SavageEd2** to be "_feature complete_" and that it "_already exceeded the goals_" originally set.

But as I see you've been adding some "_quality-of-life improvements_", I thought it wouldn't hurt to submit my request as I believe their implementation would really make **SavageEd2** hard to beat as a simple and fast text editor alternative.

1. If you have to use only one, please adhere to the international standard for date representation also known as **ISO-8601** (e.g., see https://en.wikipedia.org/wiki/ISO_8601 and https://www.w3.org/TR/NOTE-datetime); if this is not intended, at least make _date_time_ strings customizable, so they can be changed from the current hard-coded format.

2. Consider including an option/shortcut for toggling capitalization -- such as changing the capitalization of a given selection.

3. Make standard URLs and email addresses active so that an user is able to launch them in the default program just by (double or CTRL?) clicking. As a ready example, this feature was present in the minimalist [**Win32Pad**](http://www.gena01.com/win32pad/) editor over a decade ago. 

I'm not a programmer but I believe such features won't be extremely hard to implement and will enhance the appeal of **SavageEd2** a thousand-fold 😉 -- as it is already displayed prominently in well-regarded communities like [PortableFreeware.com](https://www.portablefreeware.com/?id=2186).

Thanks for your consideration and hard work.

**Comment by Androthi** [comment]
Thanks for the comments, I didn't realize anybody from the old days was still keeping an eye on SavageEd and to hear someone say SavageEd2, that's from way back :)
Those seem like reasonable requests and a fun weekend project. But do need to be mindful that I'm starting to feel the limitations of being locked in 32bits and the win32 API,  and may decide to archive the project soon, as much as it will pain me to leave HLA behind.

**Comment by midaspt** [comment]
I see -- and totally understand. It would make a fine legacy, nontheless. 😺

**Comment by Androthi** [comment]
v0.9.00 adds these features and fixes a first time startup bug. available now for beta testing in the release section.

**Comment by midaspt** [comment]
Hi there. 😎 

Just tested the new version and have couple of findings...

1. Although customizing the date format via '_savageed.ini_' appears to be working as intended, the time format is always truncated to minutes although being set to "_hh:mm:ss_";

2. I looked and looked but couldn't find the way to change a selection case;

3. A weird bug is stubbornly resetting the program window to minimal dimensions on the top left corner of the screen -- as shown in the following image (editing the INI is not making any difference).

> ![weird bug](https://user-images.githubusercontent.com/25767939/130628638-92d006ce-4469-4b27-9126-56b294c069b9.png)

Lastly, is URL activation not on your plans?

Thanks for your consideration, BTW. 👍🏽

**Comment by Androthi** [comment]
Hello, Thanks for testing.

>Although customizing the date format via 'savageed.ini' appears to be working as intended, the time format is always truncated to minutes (regardless of it being set to "hh:mm:ss");

I have not been able to repeat this. can you post a copy of your [Settings] section?
Mine as an example, looks like this.

> [Settings]
Tabs=4
Active URL=true
Date Format=MM/dd/yyyy
Time Format= hh:mm:ss
Line Break=LF
Start Position=0
Open Recent=true
Remember Position=true
Auto Indent=true
Tabs as Spaces=true
Word Wrap=false
Auto Save=false

Results in this output :

> 08/24/2021 12:15:43

Also note that I have Active URL=true, which will activate links in the editor.

>I looked and looked but couldn't find the way to change a selection case;

If you are using 0.9.10, there may have been a selection bug. Otherwise, you should be able to select some text, press ctrl+u and it it will change the selection range to upper case, and shift+ctrl+u to lower case. If you don't have a selection, it will toggle the character at the caret.

I may add these toggles and options to the menus before freezing development on this SavageEd2. I haven't had time since i've started experimentally working on a new 64bit editor built from the ground up in C++.

>A weird bug is stubbornly resetting the program window to minimal dimensions on the top left corner of the screen -- as shown in the following image (editing the INI is not making any difference).

Possibly fixed in the latest release. This can also happen if there are version updates that make changes to the INI representation internally. Sometimes I've had to delete the INI and let SavageEd create a new one. If you do this, you might want to backup some of your customizations (like custom colors) and transfer them to the new INI.

**Comment by Androthi** [comment]
selection after case change is restored in beta 0.9.30

**Comment by midaspt** [comment]
Hi. Just to confirm that selection now works as expected in v0.9.30.

> I suppose your intention is to copy a block of text after you change the case?

Or else just undo any mistaken changes...

Additionally, I was pleasantly surprised to see that the _**.LOG**_ feature is already implemented and working nicely.

May I interest you in a variation of said feature -- that I saw in **TEDNotepad**, if memory serves me well?

Depending on the placement of the "_.LOG_" string, new entries are added either at the bottom or top of the file (top when _**.LOG**_ is at bottom, bottom when _**.LOG**_ is at top).

One last observation about some of the new menu entries:  "_Set default extension_", "_Set Date Format_", and "_Set Time Format_" result in a dialog with an empty text field; it would be preferable if any of those options has been previously set, to display any value current set in order to avoid unwanted changes.

Thanks for your great work. 👍🏽

**Comment by Androthi** [comment]
You can currently use the following variation to add new entries to the top.
.LOG<

I will look into your other suggestions.

**Comment by Androthi** [comment]
v0.9.33 beta released.
