### ISSUE TITLE
Insert Date/Time enhancement

### ISSUE THREAD

**Issue by smaragdus** [Androthi/SavageEd#4]
First, I am glad that this project is still alive as I like tiny and minimalist text editors like [SavageEd](https://github.com/Androthi/SavageEd).

I would like to suggest an enhancement to **Insert Date/Time** command:

either separate command for **Insert Date** only and **Insert Time** only, example:

- **Insert Date/Time**
- **Insert Date**
- **Insert Time**

or cascading context menu **Insert** with sub-menus, example:

- **Insert**
  - **Insert Date/Time**
  - **Insert Date**
  - **Insert Time**

For me either way would be fine but I suppose that if you think the the context menu would become too cluttered you might choose the second option (cascading context menu).

However I see a possible problem for **Insert Time** command. Currently I am using these formats:

- **Date:** `yyyy-MM-dd`
- **Time:** `HH:mm:ss`

but in order to get `2021-09-28 01:37:50` in stead of `2021-09-2801:37:50` I have to put a leading space (_) in front of time format-  `_HH:mm:ss` in stead of `HH:mm:ss`. I am not a programmer and I do not know how this possible problem would be resolved since if the current time format is used (with leading space) when **Insert Time** command is executed the user would get `_01:37:50` in stead of `01:37:50`.

Regards

**Comment by Androthi** [comment]
You could place a trailing space in the date format instead of a leading space in time format, but the space or some other separator would have to be in one of them.

It is possible to add the space automatically for date/time but I don't know if I want to do this, since the user might want to have their custom separator typed in instead. I have one user who likes to place a comma.

Alternatively, it is easy to trim leading and trailing spaces when inserting only a date or only a time, but again, what if the user wants those leading and trailing spaces?

There doesn't seem to be an easy solution without implementing a complicated input analysis to predict what the user wants. This is something I want to avoid.

There is also the clutter problem as you say. Perhaps this could be solved by having something like:
Date/Time -> Insert Date/Time F5
                  -> Insert Date          Shift-F5
                  -> Inert Time           Ctrl-F5
                  -> Set Date Format...
                  -> Set Time Format...

This would clean up the context menu even more than the current state.

**Comment by smaragdus** [comment]
As I use lots of programs sometimes remembering shorcut key combinations for different programs becomes overwhelming so sometimes I prefer context menu as it is just one click away.

Anyway, inserting both date and time can be edited by deleting the date part when one needs just the time part of the command.

I have to say that separate date and time commands is not a big deal for me as I can use another program to insert them globally on any program with text field.

**Comment by midaspt** [comment]
Myself I opted for the _Date_ trailing space solution proposed by **Androthi**.

I also like his proposed keyboard shortcut solution for _Date_/_Time_ insertion, which has the added benefit of maintaining shortcut compatibility with other **Notepad** type editors.

As a further suggestion for consideration -- in order to ease user memorization of shortcuts -- maybe the currently assigned ones could be shown between brackets after their corresponding menu entry.

Selecting a menu entry and pressing a keyboard shortcut to change the assignment would be the _nec plus ultra_ of usability, IMHO.

**Comment by Androthi** [comment]
I have decided to implement this as a two part break of the Date/Time with the ctrl-F5 and shift-F5 as proposed, but keeping the format as it is now. So any leading or trailing spaces would be inserted. The context menu (which is actually the Edit menu) will also be compacted as proposed.


"As a further suggestion for consideration -- in order to ease user memorization of shortcuts -- maybe the currently assigned ones could be shown between brackets after their corresponding menu entry."

as opposed to the current way the shortcuts hints are displayed?  Please open a separate issue or start a discussion.

"Selecting a menu entry and pressing a keyboard shortcut to change the assignment would be the nec plus ultra of usability, IMHO."

The ability to add user customizable menu shortcuts is in the secret tentative v0.11.00 roadmap (as in don't hold me to it :) ). This also would be something for a dedicated discussion thread.

**Comment by Androthi** [comment]
New pre release adds distinct date and time insertion.
